var that=this;function __skpm_run(e,t){that.context=t;var r=function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/script.js")}({"./src/script.js":
/*!***********************!*\
  !*** ./src/script.js ***!
  \***********************/
/*! exports provided: default, updateArrows, updateLayerNames, settings */function(e,r,n){"use strict";n.r(r),n.d(r,"updateArrows",function(){return p}),n.d(r,"updateLayerNames",function(){return y}),n.d(r,"settings",function(){return h});var o,a=n(/*! sketch */"sketch"),i=n.n(a),s=(n(/*! util */"util").toArray,n(/*! sketch/ui */"sketch/ui")),u=n(/*! sketch/dom */"sketch/dom").Group,c=[],l=(i.a.fromNative(t.document).selectedPage,t.document.documentData()),d=t.command.valueForKey_onLayer_forPluginIdentifier("connections",l,"flowArrows"),f=l.currentPage().currentArtboard()||l.currentPage(),m=t.selection;function p(e){i.a.fromNative(e.document);i.a.UI.message("All unlocked arrows are updated 🚀")}function y(e){i.a.fromNative(e.document);i.a.UI.message("All Layers are updated 🎉")}function h(e){var t=["Link Arrow","Back Arrow"],r=s.getSelectionFromUser("Please choose link type",t),n=r[2],o=t[r[1]];n&&log(o)}r.default=function(){for(var e=0;e<f.layers().count();e++)"Arrows"==f.layers()[e].name()&&(o=f.layers()[e]);if(2==m.count())for(e=0;e<m.count();e++)if("MSSymbolInstance"==m[e].class()||"MSRectangleShape"==m[e].class()||"MSLayerGroup"==m[e].class())var r=m[0].frame(),n=r.maxX(),a=r.midY(),s=m[0].objectID(),p=m[1].frame(),y=p.minX(),h=p.midY(),b=m[1].objectID();else i.a.UI.message("Only groups, shapes and symbols are supported");else i.a.UI.message("Please select only two layers");var v,_=!1;if(d)for(var g=0;g<d.count();g++)if(!(s!=d[g].firstObject&&s!=d[g].secondObject||b!=d[g].firstObject&&b!=d[g].secondObject))for(var k=0;k<o.layers().count();k++)o.layers()[k].objectID()==d[g].line&&(_=!0,v=o.layers()[k]);if(_)v.frame().x=r.maxX(),v.frame().width=p.minX()-r.maxX(),v.style().endMarkerType=2,r.midY()<p.midY()?(v.setIsFlippedVertical(!1),v.frame().y=r.midY(),v.frame().height=p.midY()-r.midY()):(v.setIsFlippedVertical(!0),v.frame().y=p.midY(),v.frame().height=r.midY()-p.midY());else{var P=(n+y)/2,S=NSBezierPath.bezierPath();S.moveToPoint(NSMakePoint(n,a)),S.lineToPoint(NSMakePoint(P,a)),S.lineToPoint(NSMakePoint(P,h)),S.lineToPoint(NSMakePoint(y,h));var j=MSShapeGroup.layerWithPath(MSPath.pathWithBezierPath(S)),w=j.layers().firstObject().points();w[1].cornerRadius=20,w[2].cornerRadius=20,j.setName("Arrow");var A=j.style().addStylePartOfType(1);A.color=MSColor.colorWithRGBADictionary({r:.89,g:.89,b:.89,a:1}),A.thickness=2,j.style().endMarkerType=2,d&&(c=t.command.valueForKey_onLayer_forPluginIdentifier("connections",l,"flowArrows"));for(var M={firstObject:s,secondObject:b,line:j.objectID()},O=[],x=0;x<c.length;x++)O.push(c[x]);if(O.push(M),t.command.setValue_forKey_onLayer_forPluginIdentifier(O,"connections",l,"flowArrows"),o)o.addLayers([j]);else new u({parent:f,name:"Arrows",locked:!0,layers:[j]}).moveToBack()}}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("sketch")},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/dom")},"sketch/ui":
/*!****************************!*\
  !*** external "sketch/ui" ***!
  \****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/ui")},util:
/*!***********************!*\
  !*** external "util" ***!
  \***********************/
/*! no static exports found */function(e,t){e.exports=require("util")}});"default"===e&&"function"==typeof r?r(t):r[e](t)}that.onRun=__skpm_run.bind(this,"default"),that.updateArrows=__skpm_run.bind(this,"updateArrows"),that.updateLayerNames=__skpm_run.bind(this,"updateLayerNames"),that.settings=__skpm_run.bind(this,"settings");